// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   /**
    * public static final class DriveConstants {
    *   public static final int kLeftMotor1Port = 0;
    *   public static final int kLeftMotor2Port = 1;
    *   public static final int kRightMotor1Port = 2;
    *   public static final int kRightMotor2Port = 3; 
    * }
    */
    // Joystick 1 constants
    public static double kdeadzone = 0.1; // Deadzone
    public static int kinitShooter = 1;
    public static int kshiftbutton = 2;
    public static int kintakeinbutton = 9;
    public static int kintakeoutbutton = 4;
    public static int kwheelgraboutbutton = 9;
    public static int zonedown = 6;
    public static int kWinchButtonA = 10;
    public static int zoneup = 5;
    public static int kpreButton = 7;
    public static int kShootOverideButton = 8;

     // Chassis
    public static boolean kenablePID = true;
    public static double kp = 0.0002; // .005 0.012
    public static double ki = 0.0; // .1 0.0025
    public static double kd = 0.05; // .1
    public static double kgyroPIDErrorTolerance = 1.0; // in degrees
    public static double gyroPIDOutput = 0.0;
    public static double kshiftRateUp = 1200;
    public static double kshiftRateDown = 800;
    public static boolean shiftOpenState = false;    

}

